#!/usr/bin/php -q
<?php

$name = $argv[0];

if (strpos($name, '-') !== false) {
	list(,$host, $port) = explode('-', $name);
}
else {
	$host = isset($_ENV["MMC_HOST"]) ? $_ENV["MMC_HOST"] : "127.0.0.1";
	$port = isset($_ENV["MMC_PORT"]) ? $_ENV["MMC_PORT"] : 11211;
}

if(isset($argv[1]) && ($argv[1] == "autoconf")) {
	print "yes\n";
	exit;
}
elseif(isset($argv[1]) && ($argv[1] == "config")) {
	print "graph_title Memcache Get hits $host:$port\n";
	print "graph_args --base 1024\n";
	print "graph_vlabel cache hits and misses per \${graph_period}\n";
	print "graph_category memcache\n";
	print "memcache_hit.label hits\n";
	print "memcache_hit.type DERIVE\n";
	print "memcache_hit.min 0\n";
	print "memcache_hit.draw LINE1\n";
	print "memcache_hit.info Number of cache hits\n";
	print "memcache_miss.label misses\n";
	print "memcache_miss.type DERIVE\n";
	print "memcache_miss.min 0\n";
	print "memcache_miss.draw LINE1\n";
	print "memcache_miss.info Number of cache misses\n";
	exit;
}

$stats = get_mmc_stats($host, $port);
print "memcache_hit.value " . $stats["get_hits"] . "\n";
print "memcache_miss.value " . $stats["get_misses"]."\n";


function get_mmc_stats($host, $port) {
	$stats = array();

	$fp = fsockopen($host, $port, $errno, $errstr, 30);
	if ($fp) {
		fwrite($fp, "stats\n\r");
		$ret = fgets($fp, 128);
		$ret = trim($ret);
		$count = 0;
		while ($ret != 'END') {
			$count++;
			$stat = explode(" ", $ret);
			$stats[trim($stat[1])] = trim($stat[2]);
			$ret = fgets($fp, 128);
			$ret = trim($ret);
		}
		fclose($fp);
	}
	return $stats;
}
