#!/usr/bin/php -q
<?php


$name = $argv[0];

if (strpos($name, '-') !== false) {
	list(,$host, $port) = explode('-', $name);
}
else {
	$host = isset($_ENV["MMC_HOST"]) ? $_ENV["MMC_HOST"] : "127.0.0.1";
	$port = isset($_ENV["MMC_PORT"]) ? $_ENV["MMC_PORT"] : 11211;
}

if(isset($argv[1]) && ($argv[1] == "autoconf")) {
        print "yes\n";
        exit;
}
elseif(isset($argv[1]) && ($argv[1] == "config")) {
        print "graph_title Memcache Bytes Traffic $host:$port\n";
        print "graph_vlabel bytes\n";
        print "graph_category memcache\n";
        print "bytes_read.label total bytes read from network\n";
        print "bytes_read.min 0\n";
        print "bytes_read.draw AREA\n";
        print "bytes_written.label total bytes sent to network\n";
        print "bytes_written.min 0\n";
        print "bytes_written.draw STACK\n";
        exit;
}



$stats = get_mmc_stats($host, $port);
print "bytes_read.value " . $stats["bytes_read"] . "\n";
print "bytes_written.value " . $stats["bytes_written"]."\n";


function get_mmc_stats($host, $port) {
        $stats = array();

        $fp = fsockopen($host, $port, $errno, $errstr, 30);
        if ($fp) {
                fwrite($fp, "stats\n\r");
                $ret = fgets($fp, 128);
                $ret = trim($ret);
                $count = 0;
                while ($ret != 'END') {
                        $count++;
                        $stat = explode(" ", $ret);
                        $stats[trim($stat[1])] = trim($stat[2]);
                        $ret = fgets($fp, 128);
                        $ret = trim($ret);
                }
                fclose($fp);
        }
        return $stats;
}
