#!/usr/bin/php -q
<?php


$name = $argv[0];

if (strpos($name, '-') !== false) {
	list(,$host, $port) = explode('-', $name);
}
else {
	$host = isset($_ENV["MMC_HOST"]) ? $_ENV["MMC_HOST"] : "127.0.0.1";
	$port = isset($_ENV["MMC_PORT"]) ? $_ENV["MMC_PORT"] : 11211;
}

if(isset($argv[1]) && ($argv[1] == "autoconf")) {
        print "yes\n";
        exit;
}
elseif(isset($argv[1]) && ($argv[1] == "config")) {
        print "graph_title Memcache Memory Usage $host:$port\n";
        print "graph_vlabel memory usage\n";
        print "graph_category memcache\n";
        print "memcache_maxmemory.label maximun\n";
        //print "memcache_maxmemory.type DERIVE\n";
        print "memcache_maxmemory.min 0\n";
        print "memcache_maxmemory.draw LINE1\n";
        print "memcache_currentusage.label current usage\n";
        //print "memcache_currentusage.type DERIVE\n";
        print "memcache_currentusage.min 0\n";
        print "memcache_currentusage.draw AREA\n";
        exit;
}



$stats = get_mmc_stats($host, $port);
print "memcache_maxmemory.value " . $stats["limit_maxbytes"] . "\n";
print "memcache_currentusage.value " . $stats["bytes"]."\n";


function get_mmc_stats($host, $port) {
        $stats = array();

        $fp = fsockopen($host, $port, $errno, $errstr, 30);
        if ($fp) {
                fwrite($fp, "stats\n\r");
                $ret = fgets($fp, 128);
                $ret = trim($ret);
                $count = 0;
                while ($ret != 'END') {
                        $count++;
                        $stat = explode(" ", $ret);
                        $stats[trim($stat[1])] = trim($stat[2]);
                        $ret = fgets($fp, 128);
                        $ret = trim($ret);
                }
                fclose($fp);
        }
        return $stats;
}
